audit_header: false
title: Nevada Real Estate Video Blog with Blaine Moore
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Blaine Moore
  title:
  license_number:
  about_markdown: |
    There are plenty of reasons why Blaine Moore is succeeding in the real estate business, yet he’d be the first to tell you that he was just “doing what was best for my clients throughout each transaction.”

    Since the day he started as a Realtor in the Reno area, Blaine has become a respected voice in the business. Buyers and sellers will tell you that his charismatic personality is just the beginning of Blaine’s many attributes. From good-old-fashioned relationships to innovative online marketing, Blaine understands what it takes to move property in today’s market. Living life to the fullest, Blaine balances his career as a local coach and mentor and spends as much time as possible enjoying the great outdoors. With a drive to go ‘above and beyond the norm’, Blaine is ready to help you achieve your real estate dreams through Chase International’s Reno office.
  market: Nevada
  brand: Chase international
  brokerage:
  address: '985 Damonte Ranch Pkwy #110<br>Reno, NV 89521'
  phone: 775-354-6211
  phone_type:
  phone2:
  phone2_type:
  email: bmoore@chaseinternational.com
  url: http://www.nvhomelife.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.nvhomelife.com/cma/property-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.nvhomelife.com/search/advanced_search//

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.nvhomelife.com/cma/property-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.nvhomelife.com/search/advanced_search//

lender:
  show_section: true
  header_text: Preferred Lender
  headshot_path: /img/lender.jpg
  logo_path:
  logo_path_2:
  name: <br>Michelle Piccinini
  license_number: NMLS# 227880
  brand: Loan Consultant
  phone: 775-501-8546<br>

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Reno-Tahoe-Real-Estate-109871809031861/
  linkedin_url: https://www.linkedin.com/in/blaine-moore-5701b89
  gplus_url: https://plus.google.com/103240350441987139911
  youtube_url: https://www.youtube.com/channel/UC6cyX9kZsMJgqgoD2Ab-Pyg
  twitter_url: https://twitter.com/bamster21
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Blaine-Moore/
  trulia_url: http://www.trulia.com/profile/blaine-moore-agent-reno-nv-zgmcd0t2/overview
  yelp_url: https://www.yelp.com/user_details?userid=oBl9I3bU28nxtAbjdMFMCw
  podcast_url: https://itunes.apple.com/us/podcast/nevada-real-estate-podcast-with-blaine-moore/id1177552901?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#01515c'
  theme_color: '#5a5a5c'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
